<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://java.hknsoft.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://java.hknsoft.com" xmlns:intf="http://java.hknsoft.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="Servlet">

   </wsdl:portType>

   <wsdl:binding name="ServletSoapBinding" type="impl:Servlet">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="ServletService">

      <wsdl:port binding="impl:ServletSoapBinding" name="Servlet">

         <wsdlsoap:address location="http://localhost:8080/ArithmeticWeb/services/Servlet"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
